[features]
seeds = false
[programs.devnet]
mint_nft = "8By3531UQHQCB2fjpGgZDup4izzRTu12CV78gtUZKa1L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ali/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
